services:
  web:
    build:
      context: ./web
      dockerfile: docker/dev/Dockerfile
      target: dev
      args:
        - BASE_IMAGE_NODE=${BASE_IMAGE_NODE}
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    ports:
      - "5137:5137"
    environment:
      - VITE_API_URL
      - VITE_CLIENT_BASE_URL
      - VITE_IDENTITY_AUTH_URL
      - VITE_IDENTITY_ISSUER
      - VITE_IDENTITY_CLIENT_ID
      - VITE_MOCK_AUTH_ENABLED